runtime: python311
service: whatsapp-automation

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "/app/service-account.json"
  ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: gunicorn --bind :$PORT --workers 2 --timeout 120 --keep-alive 5 src.main:app 