runtime: python311
service: whatsapp-automation

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "/app/service-account.json"
  ENV: "production"
  PROJECT_ID: "your-project-id"
  OPENAI_API_KEY: "your-openai-api-key"
  SHOPIFY_API_KEY: "your-shopify-api-key"
  SHOPIFY_API_PASSWORD: "your-shopify-api-password"
  SHOPIFY_STORE_NAME: "your-shopify-store-name"
  ZOKO_API_KEY: "your-zoko-api-key"
  API_KEY: "your-api-key"
  RATE_LIMIT: "30"
  RATE_PERIOD: "60"
  CACHE_TTL: "3600"
  ZOKO_API_URL: "https://chat.zoko.io/v2/message"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: uvicorn src.main:app --host=0.0.0.0 --port=8080 